// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsUdECRhh1gpziMCb17EGFAy6J_s5vHTo',
    appId: '1:846620525638:android:82627b25394262b2017647',
    messagingSenderId: '846620525638',
    projectId: 'chatapp-ba1cb',
    databaseURL: 'https://chatapp-ba1cb-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-ba1cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCecHl2UgXMgGj47_pR6xpIUQr5N9kAJ4g',
    appId: '1:846620525638:ios:fe3d4c1b7f39cadc017647',
    messagingSenderId: '846620525638',
    projectId: 'chatapp-ba1cb',
    databaseURL: 'https://chatapp-ba1cb-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-ba1cb.firebasestorage.app',
    androidClientId: '846620525638-u7di6id3gt01m2ro866aeq9ig58hr2tn.apps.googleusercontent.com',
    iosClientId: '846620525638-bsg56gqe15qcvc4gdv8b29kb54ar1mvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpadstate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0AKlcYqHJaSICa2WHcnFI-QKkfnVYHN0',
    appId: '1:846620525638:web:d64783ae7e85afee017647',
    messagingSenderId: '846620525638',
    projectId: 'chatapp-ba1cb',
    authDomain: 'chatapp-ba1cb.firebaseapp.com',
    databaseURL: 'https://chatapp-ba1cb-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-ba1cb.firebasestorage.app',
  );
}
